---
title: Oh, Hello. I'm Kenton Hansen.
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: I make things. I make people make things. You might know me from Startup
  Wichita, the Labor Party, or some other place.
permalink: ":title/"
baseurl: 
url: 
site-twitter: kentonh
author: Kenton Hansen
author-img: kenton_thumb.jpg
about-author: I make things. I make people make things. Mostly digital things.
twitter: kentonh
facebook: 
github: kentonh
linkedin: kentonh
email: himself@kentonhansen.com
discus-identifier: 
analytics: 
markdown: kramdown
plugins:
- jekyll-paginate
plugins_dir:
- jekyll-sitemap
- jekyll-paginate
- jemoji
paginate: 8
paginate_path: "/page/:num"
exclude:
- node_modules
- gulpfile.js
- package.json
- yarn.lock
